languages:
  JavaScript: true
engines:
  # ... CONFIG CONTENT ...
  eslint:
    # ... CONFIG CONTENT ...
    enabled: false
# ... CONFIG CONTENT .
  duplication:
    # ... CONFIG CONTENT ...
    enabled: false